- name: Install Redis
  ansible.builtin.package:
    name: redis-server
    state: present

- name: Set Redis password
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    state: present
    regexp: '^requirepass\s'
    line: "requirepass {{ redis_password }}"
    backup: yes

- name: Start and enable Redis service
  ansible.builtin.systemd:
    name: redis-server
    state: started
    enabled: yes

- name: Restart Redis
  ansible.builtin.systemd:
    name: redis-server
    state: restarted
