- name: Install system packages
  ansible.builtin.apt:
    name:
      - python3
      - python3-venv
    state: present

- name: Create the Django logs directory
  ansible.builtin.file:
    path: /var/log/django
    state: directory
    mode: "0755"

- name: Create the Django application directory
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: directory
    mode: "0755"

- name: Clone the Django application
  ansible.builtin.git:
    repo: "{{ app_repo }}"
    dest: "{{ app_path }}"
    update: yes

- name: Create a virtual environment
  ansible.builtin.pip:
    chdir: "{{ app_path }}"
    virtualenv: "{{ venv_path }}"
    virtualenv_command: python3 -m venv
    requirements: "requirements.txt"

- name: Create Gunicorn configuration file
  ansible.builtin.template:
    src: "{{ playbook_dir }}/roles/app/templates/gunicorn.conf.py.j2"
    dest: "{{ app_path }}/gunicorn.conf.py"
    mode: "0644"

- name: Create the Gunicorn logs directory
  ansible.builtin.file:
    path: /var/log/gunicorn
    state: directory
    mode: "0755"

- name: Create /run directory Systemd service file
  ansible.builtin.template:
    src: "{{ playbook_dir }}/roles/app/templates/gunicorn-run-dir.service.j2"
    dest: "{{ run_dir_maker_config_path }}"
    mode: "0644"

- name: Create Gunicorn Systemd service file
  ansible.builtin.template:
    src: "{{ playbook_dir }}/roles/app/templates/gunicorn.service.j2"
    dest: "{{ gunicorn_config_path }}"
    mode: "0644"

- name: Reload Systemd configuration
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start run dir service
  ansible.builtin.systemd:
    name: gunicorn-run-dir
    state: started
    enabled: yes

- name: Enable and start Gunicorn service
  ansible.builtin.systemd:
    name: gunicorn
    state: started
    enabled: yes

- name: Restart Gunicorn
  ansible.builtin.systemd:
    name: gunicorn
    state: restarted

- name: Run Django migrations
  ansible.builtin.command:
    cmd: "{{ venv_path }}/bin/python manage.py migrate"
    chdir: "{{ app_path }}"
  environment:
    DJANGO_SETTINGS_MODULE: "myapp.settings"
